# Generated by Django 5.1.3 on 2026-04-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image2_product_image3_product_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_listing_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
