# Generated by Django 5.1.3 on 2026-04-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_product_ebay_listing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField()),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eBay auth token',
                'verbose_name_plural': 'eBay auth token',
            },
        ),
        migrations.CreateModel(
            name='EbayCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_store_category_id', models.CharField(max_length=64, unique=True)),
                ('ebay_store_category_name', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pokebin_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ebay_mappings', to='store.category')),
            ],
            options={
                'verbose_name': 'eBay category mapping',
                'verbose_name_plural': 'eBay category mappings',
                'ordering': ['ebay_store_category_name', 'ebay_store_category_id'],
            },
        ),
        migrations.CreateModel(
            name='EbayListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ebay_store_category_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ebay_last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=32)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebay_listing', to='store.product')),
            ],
            options={
                'verbose_name': 'eBay listing',
                'verbose_name_plural': 'eBay listings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
