# Generated by Django 5.1.3 on 2024-12-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_id_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='id',
        ),
    ]
