# Generated by Django 5.1.3 on 2024-12-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_rename_order_number_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]


